### ISSUE TITLE
RSE Educational Resource Discoverability

### ISSUE THREAD

**Issue by fiveop** [DE-RSE/un-deRSE23-breakouts#18]
One of the tasks of RSE (associated) departments is education.
This duty necessitates the creation and use of educational resources.
As for other products of work in academia, there are open publications of such resources: open educational resources (OER).
For other products, such as software, articles, and data, there exist tools and standards that help with discoverability (or they are actively worked on).

I want to use this session to discuss…

- …what standards and tools already exist that help with discoverability of open RSE educational resources. These can come from other or more broader fields, for example education in general. Even if they serve only as (good) examples, they can be helpful.
- …what information about a educational resources we are interested in, when we are searching for them. What metadata needs to be attached to OER, so that we can easily find what we are looking for. The “we”, in this case, covering both educators and learners.
- …what is missing and how could we, as a community, go about creating or adapting tools and standards to satisfy our needs.

It would be helpful if those that are interested in participating will (just like I) prepare answers or contributions to the first two questions.

---

I expect each of the three questions to take up a similar amount of time. Given a 90 minute slot and taking into account sufficient time for breaks and logistics, that would result in around 20 minutes of discussion and 5 minutes of consolidation per question.

The goal is to create the basis for an (initially) informal group to continue to work on this topic.

--- 

Potential Collaborators:

@schlauch
@tobyhodges

**Comment by HeidiSeibold** [comment]
I added a [label](https://github.com/DE-RSE/un-deRSE23-breakouts/labels) to this break-out. Can you check if you feel it is appropriate and change it if not? Let me know if you have any questions.

**Comment by HeidiSeibold** [comment]
So what I need from you to be able to make a decision on this breakout are the following infos:


### Who could be interested in collaborating on this?

@schlauch
@tobyhodges

### How much time do you need for this?
90 minutes

### Abstract

One of the tasks of RSE (associated) departments is education. This duty necessitates the creation and use of educational resources. As for other products of work in academia, there are open publications of such resources: open educational resources (OER). For other products, such as software, articles, and data, there exist tools and standards that help with discoverability (or they are actively worked on).

I want to use this session to discuss…

- …what standards and tools already exist that help with discoverability of open RSE educational resources. These can come from other or more broader fields, for example education in general. Even if they serve only as (good) examples, they can be helpful.
- …what information about a educational resources we are interested in, when we are searching for them. What metadata needs to be attached to OER, so that we can easily find what we are looking for. The “we”, in this case, covering both educators and learners.
- …what is missing and how could we, as a community, go about creating or adapting tools and standards to satisfy our needs.

It would be helpful if those that are interested in participating will (just like I) prepare answers or contributions to the first two questions.

**Comment by fiveop** [comment]
I added the collaborators to the issue description and will add an abstract tomorrow.

If both https://github.com/DE-RSE/un-deRSE23-breakouts/issues/17 and this proposal get into the program, could you please not schedule them at the same time.

**Comment by fiveop** [comment]
Is the part above the first horizontal line in the issue description too long? Otherwise I would submit that as the abstract.

**Comment by HeidiSeibold** [comment]
That is fine :)

Can you fill everything in by Tuesday morning? That would be excellent 😃

**Comment by fiveop** [comment]
Done (I think)

**Comment by CaptainSifff** [comment]
Just making you aware of the collection we did in february: https://pad.gwdg.de/teaching-RSE-resource-pad

**Comment by fiveop** [comment]
Thank you

**Comment by pancetta** [comment]
Hi! I just added the "Accepted" label to this BOS. Welcome on board!
https://un-derse23.sciencesconf.org/program

**Comment by pancetta** [comment]
Hi all, the unconference is only 3 weeks away now! On day 1 there will be a breakout blitz where all session organizers should advertise their sessions. 1 minute, 1 slide, let people know what you intend to do. Please prepare this slide in advance and add it right here (PDF please), by **September 20**.

**Comment by fiveop** [comment]
[rse_oer_disc_showcase.pdf](https://github.com/DE-RSE/un-deRSE23-breakouts/files/12648528/rse_oer_disc_showcase.pdf)

**Comment by pancetta** [comment]
Here is the main hub for taking notes: https://pad.gwdg.de/FkFJTslFQhq-UF3Es6q4rw#

**Comment by pancetta** [comment]
Have fun with the session(s)! Please add the pad you're using also here for people to see what you did. 

If possible, please prepare a 1 minute wrap up of your session for the farewell session on Thursday afternoon! What did you do in the session, how would you like to continue, how can people contribute after the unconference etc. We'll go through the blitz slides again one by one as in the blitz session.

**Comment by fiveop** [comment]
https://pad.gwdg.de/5V03P-HDQSSMRliYpai6Nw?view

**Comment by fiveop** [comment]
Report: https://zenodo.org/records/10283738
